apiVersion: v1
kind: Pod
metadata:
  name: pod-tomcat-volume-hostpath
  namespace: default
  labels:
    app: tvh
spec:
  containers:
  - name: tomcat-volume-hostpath
    image: tomcat
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: app-logs
      # 掛載到容器的位置
      mountPath: /usr/local/tomcat/logs
  - name: busybox-volume-hostpath
    image: busybox
    command: ["sh","-c","tail -f /logs/catalina*.log"]
    volumeMounts:
    - name: app-logs
      # 掛載到容器的位置
      mountPath: /logs
  volumes:
  - name: app-logs
    hostPath:
      path: /applogdata
      type: Directory

    
