apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbtomcat-deployment
  labels: # FOR 查詢使用
    app: sbtomcat-d
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels: # replicas作用的pod的label
      app: sbtomcat-v3-pod
  template:
    metadata:
      labels:
        app: sbtomcat-v3-pod
    spec:
      containers:
      - name: sbtomcat-v3
        image: adolphgirl/sbtomcat:v4
        ports:
          - containerPort: 8080
            protocol: TCP
    
